spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/db_product
    username: product
    password: product

logging:
  level:
    org.springframework: INFO
    net.elau.example.debeziumcdckafka: DEBUG